# 1.)  usando las ventajas de numpy

In [2]:
#!/usr/bin/env python
#-*-coding: utf-8-*-

import numpy as np

dx = float(input("ingrese número para dx"))

i = int(input("ingrese cantidad de datos"))

n = np.linspace(0.0, i, i/dx)

def fun(x):
    y = np.sin(x)*np.log(1*x+1)*np.sinh(x)
    return y

resultado = np.array([i]), np.array([n]), np.array([fun(n)])

resultado

ingrese número para dx0.1
ingrese cantidad de datos5


/home/ssy/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: DeprecationWarning: object of type <class 'float'> cannot be safely interpreted as an integer.
  # Remove the CWD from sys.path while we load stuff.


(array([5]),
 array([[ 0.        ,  0.10204082,  0.20408163,  0.30612245,  0.40816327,
          0.51020408,  0.6122449 ,  0.71428571,  0.81632653,  0.91836735,
          1.02040816,  1.12244898,  1.2244898 ,  1.32653061,  1.42857143,
          1.53061224,  1.63265306,  1.73469388,  1.83673469,  1.93877551,
          2.04081633,  2.14285714,  2.24489796,  2.34693878,  2.44897959,
          2.55102041,  2.65306122,  2.75510204,  2.85714286,  2.95918367,
          3.06122449,  3.16326531,  3.26530612,  3.36734694,  3.46938776,
          3.57142857,  3.67346939,  3.7755102 ,  3.87755102,  3.97959184,
          4.08163265,  4.18367347,  4.28571429,  4.3877551 ,  4.48979592,
          4.59183673,  4.69387755,  4.79591837,  4.89795918,  5.        ]]),
 array([[  0.00000000e+00,   1.01169962e-03,   7.73484241e-03,
           2.50242664e-02,   5.70063562e-02,   1.07229913e-01,
           1.78756255e-01,   2.74202998e-01,   3.95749987e-01,
           5.45112472e-01,   7.23484686e-01,   9.314559

# 1.) sin usar las ventajas de numpy

In [46]:
s = []
x = []
len_i = int(i/dx)
for j in range(len_i):
    s.append(fun(j))
    x.append(j)

print(s)    
print (x)
print (i)

[0.0, 0.68545165661172824, 3.6231077939066294, 1.9598356553963283, -33.239845826746333, -127.49311067713298, -109.67496431296621, 749.09042030807382, 3240.0658520882712, 3844.6615859877052, -14366.824510963215, -74390.097885684241, -111998.274315748, 245283.91631098659, 1613061.8144451873, 2946987.6672909348, -3624162.4923424888, -33560844.961893409, -72594847.771188945, 40068562.106718332, 674254036.6702224, 1705319807.3020387, -49746453.731466658, -13103515600.101971, -38607157742.287903, -15524788369.950539, 245960506830.95093, 847776355970.06958, 659652259906.58374, -4436805268992.502, -18129005443259.996, -20338374509934.973, 76122961006848.391, 378421966298076.25, 548767095092713.56, -1216790079889321.0, -7719760246773338.0, -13716819065283550.0, 17294020833207346.0, 1.5393384061337949e+17, 3.2565921448798259e+17, -1.8967492687809619e+17, -2.9978325098976568e+18, -7.4406580558596506e+18, 4.330041709050983e+17, 5.6904512001884373e+19, 1.6485349937530461e+20, 6.1741957990623158e+19

# 2.) organizando listas

In [23]:
lista = [45,-3,2,0,23,-56] #pueden cambiar la lista si así lo desean
nueva_list = []

while lista:
    minimo = lista[0]   
    for x in lista: 
        if x < minimo:
            minimo = x
    nueva_list.append(minimo)
    lista.remove(minimo)    

print(nueva_list)

[-56, -3, 0, 2, 23, 45]


# 3.) serie de Taylor

In [32]:
def factorial(x): 
    factorial = 1 
    while (x >1):
        factorial = factorial * x 
        x = x - 1                  
    return factorial                

grado = float(input("ingrese grado(en radianes) para comprobar la serie"))

repeticiones = int(input("ingrese el n para la serie"))

sumatoria = 1.0
contador = 0.0
coseno = 0.0
cosenofinal = 0.0

while(contador < repeticiones):
    dividendo = float((grado**(2*contador)))
    divisor = float((factorial(2*contador)))
    sumatoria = float((dividendo/divisor))
    contador = contador+1
    if (contador % 2 == 0):
        coseno += sumatoria
    else:
        coseno -= sumatoria
            
        
cosenofinal= (coseno*(-1))

print(cosenofinal)

print("Resultado usando numpy", np.cos(grado))

ingrese grado(en radianes) para comprobar la serie1
ingrese el n para la serie5
0.5403025793650793
Resultado usando numpy 0.540302305868
